#!/usr/bin/env bash

set -e

GREEN='\033[0;32m'
NC='\033[0m'

CONFIG="install.conf.yaml"
DOTBOT_DIR="dotbot"

DOTBOT_BIN="bin/dotbot"
BASEDIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

fecho() {
  echo -e
  echo -e "${1}${2}${NC}"
}

cd "${BASEDIR}"
git -C "${DOTBOT_DIR}" submodule sync --quiet --recursive
git submodule update --init --recursive "${DOTBOT_DIR}"

"${BASEDIR}/${DOTBOT_DIR}/${DOTBOT_BIN}" -d "${BASEDIR}" -c "${CONFIG}" "${@}"

if ! command -v uv >/dev/null 2>&1; then
  echo
  echo "Installing uv"
  sudo dnf install uv
fi

if ! command -v nvim >/dev/null 2>&1; then
  echo
  echo "Installing nvim"
  curl -LO https://github.com/neovim/neovim/releases/latest/download/nvim-linux-x86_64.tar.gz
  sudo rm -rf /opt/nvim-linux-x86_64
  sudo tar -C /opt -xzf nvim-linux-x86_64.tar.gz
  rm nvim-linux-x86_64.tar.gz
fi

if [ ! -f "$HOME/.fonts/JetBrainsMonoNerdFont-Regular.ttf" ]; then
  echo
  echo "Installing JetBrains Mono NerdFont"
  if [ ! -d "$HOME/.fonts" ]; then
    mkdir "$HOME/.fonts"
  fi
  curl -LO https://github.com/ryanoasis/nerd-fonts/releases/download/v3.4.0/JetBrainsMono.zip
  unzip JetBrainsMono.zip "JetBrainsMonoNerdFont-Regular.ttf" -d "$HOME/.fonts"
  fc-cache -fv
  rm JetBrainsMono.zip
fi

if [ ! -d "$HOME/.nvm" ]; then
  echo
  echo "Installing nvm"
  curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.40.5/install.sh | bash
fi
