#!/bin/bash

VENV_PATH="$HOME/.envs/ansible"

## Ensure Python is installed
if ! command -v python3 &>/dev/null; then
  echo "Python is not installed. Installing Python..."
  sudo apt update
  sudo apt install -y python3
fi

## Ensure pip is installed
if ! command -v pip3 &>/dev/null; then
  echo "Pip is not installed. Installing Pip..."
  sudo apt update
  sudo apt install -y pip3
fi

## Install Ansible
if ! command -v ansible &>/dev/null; then
  echo "Ansible is not installed. Installing Ansible..."
  if [ ! -d "$VENV_PATH" ]; then
    echo "Creating virtual environment for Ansible..."
    mkdir ~/.envs
    python3 -m venv "$VENV_PATH"
  else
    echo "Virtual environment already exists."
  fi
  source "$VENV_PATH/bin/activate"
  pip install ansible
fi

## Run Ansible playbook
echo "Running Ansible playbook..."
ansible-playbook setup.yml --ask-become-pass
deactivate
